const appname = "Whole Choice Seller App",
    login = "Login",
    welcome = "Hi, Welcome to",
    email = "Email",
    password = "Password",
    forgotPassword = "Forgot Password?,",
    emailHint = "eg.talha@gmail.com",
    passwordHint = "* * * * * *",
    logout = "Logout",
    confirmPass = "Confirm Password",
    changeImage = "Change Image",
    messages = "Messages",
    shopSettings = "Shope Settings",
    editProfile = " Edit Profile",
    loginTo = "Login to your account",
    dashboard = 'Dashboard',
    rating = "Rating",
    totalSale = "Total Sales",
    popular = "Popular Products",
    unPaid = "Unpaid",
    orders = "Orders",
    products = 'Products',
    settings = "Settings",
    featured = "Featured",
    edit = "Edit",
    save = "Save",
    remove = "Remove",
    name = "Username",
    chat = "Chats",
    orderDetail = "Order Detail",
    anyProblem = "In case of any difficulty, contact administration",
    credit = "@Gul Faraz Ahmed";
//  Shope Settibgs strings

const nameHint = "eg. Vendor Name",
    shopDescHint = "Enter your Shope description",
    shopeWebsiteHint = "e.g vendor.wholechoice.com",
    shopeMobileHint = "e.g, 03110064957",
    shopeAddressHint = "e.g Near Vehari Bazar",
    description = "Description",
    mobile = "Shope Mobile No",
    website = "shope Website",
    shopeName = "shope Name",
    shopeAddress = "shope Address";

// Order place detaile
const d1 = "", d2 = "", title1 = "", title2 = "";
